---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/artful-gopher/c3po.git 
    branch: master

- name: only-weekdays-at-1pm-pst
  type: time
  icon: clock-outline
  source:
    #start: 1:00 PM
    #stop: 1:15 PM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    interval: 2m
    location: America/Los_Angeles

jobs:
  - name: job-send-reminder
    public: true
    plan:
      - get: only-weekdays-at-1pm-pst
        trigger: true
      - get: source-code
      - task: task-send-reminder
        file: source-code/task-scripts/task.yml
        params:
          TZ: ((TZ))
          CHANNEL_ID: ((CHANNEL_ID))
          SLACK_API_TOKEN: ((SLACK_API_TOKEN))
          GOOGLE_SHEET_URL: ((GOOGLE_SHEET_URL))
          SLACK_HANDLE: ((SLACK_HANDLE))
        input_mapping:
          c3po-files: source-code
