---
resources:
  - name: only-weekdays-at-1pm-pst
    type: time
    icon: clock-outline
    source:
      #start: 1:00 PM
      #stop: 1:15 PM
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]
      interval: 5m
      location: America/Los_Angeles
jobs:
  - name: job-send-reminder
    public: true
    plan:
      - get: only-weekdays-at-1pm-pst
        trigger: true 
      - task: task-send-reminder
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: artfulgopher/tobot_env
              tag: "1.0"
          run:
            path: python
            args: [--version]
